# Converts a binary file to a C source header with a const array.
# Invoked with -DIN=<binary> -DOUT=<header> -DNAME=<array-name>
file(READ "${IN}" hex HEX)
string(LENGTH "${hex}" hexlen)
math(EXPR bytelen "${hexlen} / 2")

file(WRITE "${OUT}" "// Generated by embed_binary.cmake from ${IN}\n")
file(APPEND "${OUT}" "#pragma once\n")
file(APPEND "${OUT}" "#ifdef __cplusplus\n")
file(APPEND "${OUT}" "extern \"C\" {\n")
file(APPEND "${OUT}" "#endif\n")
file(APPEND "${OUT}" "extern const unsigned char ${NAME}[];\n")
file(APPEND "${OUT}" "extern const unsigned int ${NAME}_len;\n")
file(APPEND "${OUT}" "#ifdef __cplusplus\n")
file(APPEND "${OUT}" "}\n")
file(APPEND "${OUT}" "#endif\n")
